### ISSUE TITLE
RNG too strong

### ISSUE THREAD

**Issue by akostadinov** [joellord/subsquirrel#4]
Hi, I notice that RNG is too random. After 150 I got distracted and managed to unsubscribe:
![Screenshot_20200710_111848](https://user-images.githubusercontent.com/1408661/87133035-6c40dc00-c29f-11ea-9282-11cdcf7f6ab9.png)

The RNG must make sure cup hits you in case you approach 0 points lest you manage to unsubscribe.

**Comment by joellord** [comment]
Actually, that would be an issue for @sebastienblanc, he is the creator of https://scratch.mit.edu/projects/327299289/ Unsubquirrel... The Game.

**Comment by akostadinov** [comment]
Do you know how do I file issue with him? Or we hope he notices here?

**Comment by sebastienblanc** [comment]
I'm here  :) ! You can fork any Scratch project, it's called "remix", maybe I will tweak it a bit during my PTO
